CREATE TABLE TBL_ORDEM_SERVICO
(
    ID_ORDEM_SERVICO BIGINT PRIMARY KEY IDENTITY,
    ID_EQUIPAMENTO   BIGINT       NOT NULL,
    ID_CLIENTE       BIGINT       NOT NULL,
    DT_ENTRADA       DATETIME     NOT NULL,
    DT_PREVISAO      DATETIME,
    TX_OBSERVACAO    VARCHAR(300),
    TX_DEFEITO       VARCHAR(100) NOT NULL,
    NR_PRIORIDADE    SMALLINT     NOT NULL,
    DT_SAIDA         DATETIME,
    TX_STATUS        VARCHAR(12) NOT NULL,
    FOREIGN KEY (ID_EQUIPAMENTO) REFERENCES TBL_EQUIPAMENTO (ID_EQUIPAMENTO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE (ID_CLIENTE)
);

INSERT INTO TBL_ORDEM_SERVICO(ID_EQUIPAMENTO,ID_CLIENTE,DT_ENTRADA,DT_PREVISAO,TX_DEFEITO,NR_PRIORIDADE,DT_SAIDA,TX_STATUS) VALUES (1,1,'2023-07-03 09:01:43',NULL,'Computador não liga, após instalação de programa',0,'2023-07-10 14:13:09','CONCLUIDO');
INSERT INTO TBL_ORDEM_SERVICO(ID_EQUIPAMENTO,ID_CLIENTE,DT_ENTRADA,DT_PREVISAO,TX_DEFEITO,NR_PRIORIDADE,DT_SAIDA,TX_STATUS) VALUES (2,2,'2023-07-15 11:32:23',NULL,'Troca de memória',2,NULL,'BLOQUEADO');

CREATE TABLE TBL_REL_OS_TECNICO
(
    ID_ORDEM_SERVICO BIGINT NOT NULL,
    ID_TECNICO       BIGINT NOT NULL,
    FOREIGN KEY (ID_ORDEM_SERVICO) REFERENCES TBL_ORDEM_SERVICO (ID_ORDEM_SERVICO),
    FOREIGN KEY (ID_TECNICO) REFERENCES TBL_TECNICO (ID_TECNICO)
);

INSERT INTO TBL_REL_OS_TECNICO(ID_ORDEM_SERVICO,ID_TECNICO) VALUES (1,1);
INSERT INTO TBL_REL_OS_TECNICO(ID_ORDEM_SERVICO,ID_TECNICO) VALUES (1,2);
INSERT INTO TBL_REL_OS_TECNICO(ID_ORDEM_SERVICO,ID_TECNICO) VALUES (2,1);

CREATE TABLE TBL_ITEM_SERVICO
(
    ID_ITEM_SERVICO  BIGINT PRIMARY KEY IDENTITY,
    ID_ORDEM_SERVICO BIGINT NOT NULL,
    ID_SERVICO       BIGINT NOT NULL,
    NR_VALOR         FLOAT  NOT NULL,
    FOREIGN KEY (ID_ORDEM_SERVICO) REFERENCES TBL_ORDEM_SERVICO (ID_ORDEM_SERVICO),
    FOREIGN KEY (ID_SERVICO) REFERENCES TBL_SERVICO (ID_SERVICO)
);

INSERT INTO TBL_ITEM_SERVICO(ID_ORDEM_SERVICO,ID_SERVICO,NR_VALOR) VALUES (1,3,50.00);
INSERT INTO TBL_ITEM_SERVICO(ID_ORDEM_SERVICO,ID_SERVICO,NR_VALOR) VALUES (1,1,50.00);
INSERT INTO TBL_ITEM_SERVICO(ID_ORDEM_SERVICO,ID_SERVICO,NR_VALOR) VALUES (1,2,100.00);
INSERT INTO TBL_ITEM_SERVICO(ID_ORDEM_SERVICO,ID_SERVICO,NR_VALOR) VALUES (1,4,30.00);
INSERT INTO TBL_ITEM_SERVICO(ID_ORDEM_SERVICO,ID_SERVICO,NR_VALOR) VALUES (2,11,30.00);
